### ISSUE TITLE
Cannot read property 'client' of undefined

### ISSUE THREAD

**Issue by venkyabburi** [NathanaelA/nativescript-websockets#74]
LOG from device Abburi: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
LOG from device Abburi: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'client' of undefined
LOG from device Abburi: at Module../app/home/home.component.ts (file:///data/data/org.nativescript.preview/files/app/2.js:53:81)
LOG from device Abburi: at __webpack_require__ (file:///data/data/org.nativescript.preview/files/app/runtime.js:751:30)
LOG from device Abburi: at fn (file:///data/data/org.nativescript.preview/files/app/runtime.js:121:20)
LOG from device Abburi: at Module../app/home/home-routing.module.ts (file:///data/data/org.nativescript.preview/files/app/2.js:13:73)
LOG from device Abburi: at Object.../node_modules/nativescript-websockets/websockets.js (file:///data/data/org.nativescript.preview/files/app/vendor.js:584:37)
LOG from device Abburi: at fn (file:///data/data/org.nativescript.preview/files/app/runtime.js:121:20)
LOG from device Abburi: TypeError: Cannot read property 'client' of undefined
LOG from device Abburi: at __webpack_require__ (file:///data/data/org.nativescript.preview/files/app/runtime.js:751:30)
LOG from device Abburi: at __webpack_require__ (file:///data/data/org.nativescript.preview/files/app/runtime.js:751:30)
LOG from device Abburi: at fn (file:///data/data/org.nativescript.previ...

**Comment by mrwhy-orig** [comment]
I'm having the same problem here. I have to admit that I am new to nativescript. 

I installed the Plugin V1.5.4 by the tns plugin add command. Then I imported the module in my Basic Vue template and run the app by using tns preview.  

I've seen #37 but couldn't get it working, probably because my lag of nativescript knowledge. I added the suggestions to my app.gradle which didn't help in any way.

**Comment by mrwhy-orig** [comment]
Ok... Found it... not native modules in preview app ... makes sense...

**Comment by h3xus** [comment]
I got the same issue on preview but also after build to android using plugin 1.5.5 for android 9

 > Cannot read property 'client' of undefined

StackTrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.preview/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
Error: Building UI from XML. @app-root.xml:10:2
 > Cannot read property 'client' of undefined
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3021)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3156)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:205)
        at android.app.ActivityThread.main(ActivityThread.java:6991)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
Error: Building UI from XML. @app-root.xml:10:2
 > Cannot read property 'client' of undefined
        at com.tns.Runtime.callJSMethodNative(Native Method)
        at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
        at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
        at com.tns.Runtime.callJSMethod(Runtime.java:1160)
        at com.tns.Runtime.callJSMethod(Runtime.java:1138)
        at com.tns.Runtime.callJSMethod(Runtime.java:1134)
        at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:20)
        at android.app.Activity.performCreate(Activity.java:7159)
        at android.app.Activity.performCreate(Activity.java:7150)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3001)
        ... 11 more

**Comment by NathanaelA** [comment]
NativeScript PREVIEW cannot support Websockets!    You must either do a cloud build or a local build; Preview cannot use native "compiled" modules of which NS-Websocket is one of them...
